[package]
name = "future-contest-2022-qual"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = "0.4"
rand = "0.8"

[profile.release]
lto = true
panic = 'abort'
