[package]
name = "abc146"
version = "0.1.0"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "0.4.1"

[profile.release]
lto = true
panic = 'abort'
